name: CI

on: [push]

jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install wabt
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - uses: actions/setup-go@v1
      with:
        go-version: '1.14.5'
    - uses: actions/cache@v1
      with:
        path: ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-
    - name: build
      run: make build
    - name: test
      run: make test
    - name: check tidy
      run: make check-tidy
    - name: check headers
      run: make check-headers

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: golangci/golangci-lint-action@v1
        with:
          version: v1.26
